DROP TABLE IF EXISTS ROBOT;

DROP TABLE IF EXISTS ROBOT_TYPE;

CREATE TABLE ROBOT
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    robotTypeId INT
);

CREATE TABLE ROBOT_TYPE
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    view VARCHAR2(50) NOT NULL
);